<!doctype html>
<html lang="th"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>เชื่อมต่อ AI แบบง่าย · Management Docs</title>
<style>
:root{color-scheme:light;--ink:#1b302d;--muted:#627571;--line:#dfe7e4;--green:#08745e}*{box-sizing:border-box}body{margin:0;color:var(--ink);background:#fff;font-family:system-ui,sans-serif;line-height:1.8}a{color:var(--green);text-decoration:none}a:hover{text-decoration:underline}header{border-bottom:1px solid var(--line);padding:22px 5vw;display:flex;align-items:center;justify-content:space-between;gap:20px}.brand{font-weight:700;color:var(--ink)}.layout{max-width:1240px;margin:auto;display:grid;grid-template-columns:240px 1fr;gap:70px;padding:60px 32px}nav{border-right:1px solid var(--line);padding-right:24px;position:sticky;top:24px;height:fit-content}nav a{display:block;font-size:14px;margin:16px 0}article{max-width:760px;min-width:0}.eyebrow{font-size:12px;font-weight:600;letter-spacing:.15em;color:var(--green)}h1{font-size:42px;line-height:1.35;letter-spacing:-.03em;margin:14px 0 24px}h2{font-size:25px;letter-spacing:-.02em}p,li{color:var(--muted)}.lead{font-size:19px;line-height:1.9}.toolbar{display:flex;flex-wrap:wrap;gap:12px;margin:28px 0}button,.button{cursor:pointer;padding:12px 18px;border:1px solid var(--line);border-radius:10px;background:white;color:var(--ink);font:inherit;font-size:14px;font-weight:600;display:inline-flex;align-items:center;gap:8px}.primary{background:var(--green);color:white;border-color:var(--green)}section{border-top:1px solid var(--line);padding:24px 0;margin-top:36px;scroll-margin-top:20px}.note{background:#f1f7f5;padding:20px 24px;border-radius:12px;font-size:14px}.terminal{border:1px solid #273e38;border-radius:12px;overflow:hidden;margin:20px 0;background:#142821;color:#d6ece2}.terminal header{padding:12px 18px;border-color:#30483e;font-family:monospace;font-size:12px}.terminal pre{margin:0;padding:20px;overflow-wrap:anywhere;white-space:pre-wrap;font-size:13px;line-height:1.8}.terminal button{padding:6px 12px;background:#263d34;color:white;border-color:#3b5548;font-size:12px}details{border-bottom:1px solid var(--line);padding:16px 0}summary{cursor:pointer;font-weight:600}code{overflow-wrap:anywhere;font-size:.9em}button:focus-visible,a:focus-visible{outline:3px solid #7bcbb5;outline-offset:4px}@media(max-width:850px){.layout{display:block;padding:32px 22px}nav{position:static;border:0;display:flex;flex-wrap:wrap;gap:14px;padding:0;margin-bottom:28px}nav a{margin:0}h1{font-size:32px}header{padding:18px 22px}}
</style></head><body>
<header><a class="brand" href="/docs/agent-setup">Aion3 / Docs</a><a href="/admin/ai-setup">เปิดเชื่อมต่อ AI ↗</a></header>
<div class="layout"><nav aria-label="เนื้อหาคู่มือ"><a href="#connect">เชื่อมต่อครั้งแรก</a><a href="#permissions">สิทธิ์และข้อเสนอแก้ไข</a><a href="#help">แก้ปัญหา</a><a href="/admin/ai-setup?advanced=1">Advanced · Local CLI ↗</a><a href="/docs/remote-mcp.md">อ่าน Markdown ↗</a></nav>
<article><div class="eyebrow">INTEGRATIONS / REMOTE MCP</div><h1>เชื่อม AI กับข้อมูลธุรกิจ<br>โดยไม่ต้องคัดลอก key</h1><p class="lead">ใช้บัญชีเดิมล็อกอินบนเว็บ Management แล้วกดอนุญาต แอป AI จะรับสิทธิ์เชื่อมต่อให้เองผ่าน OAuth</p>
<div class="toolbar"><a class="button primary" href="/admin/ai-setup">เริ่มเชื่อมต่อ →</a><button id="copy-page">Copy page</button></div><p id="copy-status" role="status"></p>
@unless($remoteEnabled)<div class="note">Remote MCP ยังไม่เปิดในสภาพแวดล้อมนี้ คู่มือนี้อธิบายวิธีใช้เมื่อผู้ดูแลเปิดบริการแล้ว ใช้วิธีเดิมได้ที่ Advanced</div>@endunless
<section id="connect"><div class="eyebrow">GET CONNECTED</div><h2>แค่ 3 ขั้นตอน</h2>
<h3>1. เพิ่ม Management ในแอป AI</h3><p>เปิดการตั้งค่าการเชื่อมต่อของแอปที่ใช้ เช่น Apps, Connectors หรือ MCP แล้วเพิ่ม Server URL ด้านล่าง เลือก OAuth หากแอปถามวิธียืนยันตัวตน</p>
<div class="terminal"><header><span>SERVER URL</span><button id="copy-url">Copy</button></header><pre id="server-url">{{ $baseUrl }}/mcp</pre></div>
<p>หรือใช้ปุ่ม Copy prompt ในหน้าเชื่อมต่อ AI เพื่อให้ agent ช่วยตั้งค่า การวาง prompt อย่างเดียวไม่ใช่การติดตั้ง connector และบางแอปต้องเพิ่มด้วยตัวเองก่อน</p>
<h3>2. ล็อกอินบนเว็บเรา แล้วกดอนุญาต</h3><p>แอปจะเปิดหน้า Management ให้กรอกอีเมลและรหัสผ่านเดิมด้วยตัวเอง ตรวจชื่อแอปและรายการสิทธิ์ก่อนกดอนุญาต ถ้าล็อกอินอยู่แล้ว อาจเห็นหน้าอนุญาตได้ทันที</p>
<div class="note">ไม่ต้องส่งรหัสผ่าน, key หรือรหัสยืนยันในแชต AI และอย่าให้ AI เข้าไปอ่านข้อมูลลับใน browser หรือเครื่องคุณ</div>
<h3>3. กลับไปที่ AI แล้วลองใช้งาน</h3><p>บอก AI ว่า “ช่วยดูว่ามีเอกสารอะไรบ้าง” ต้องมีผลจากเครื่องมือจริงก่อนถือว่าเชื่อมสำเร็จ รายการว่างก็เป็นผลที่ถูกต้อง ไม่ได้แปลว่าการเชื่อมต่อล้มเหลว</p></section>
<section id="permissions"><h2>AI ทำอะไรได้บ้าง?</h2><p>สิทธิ์พื้นฐานอ่านชื่อและสถานะเอกสารเท่านั้น ไม่อ่านไฟล์ PDF หากอนุญาตสิทธิ์เพิ่มเติม AI สามารถค้นข้อมูลและส่งข้อเสนอเพิ่ม แก้ไข เก็บเข้าคลัง หรือเรียกคืนรายการในหมวดที่ได้รับอนุญาต</p><p><strong>ข้อเสนอไม่ใช่การบันทึกข้อมูลจริง</strong> คุณยังเป็นคนตรวจ อนุมัติ และสั่งใช้ข้อเสนอในระบบ การเผยแพร่ต้องทำแยกต่างหาก ไม่มีสิทธิ์ SQL หรือเครื่องมือให้ AI อนุมัติเอง</p><p>การเชื่อมต่อมีอายุสูงสุด 7 วัน ระบบต่ออายุ token ย่อยให้ได้ระหว่างนั้น เมื่อครบกำหนดให้เชื่อมต่อและอนุญาตใหม่ ยกเลิกได้ที่หน้าเชื่อมต่อ AI ทุกเวลา</p><a href="/admin/agent-changes">เปิดข้อเสนอรอตรวจ →</a></section>
<section id="help"><h2>ถ้ายังเชื่อมไม่ได้</h2><details><summary>AI บอกว่าเพิ่ม connector ให้ไม่ได้</summary><p>ไปเพิ่ม Server URL ในการตั้งค่าของแอปก่อน ฟีเจอร์นี้ขึ้นอยู่กับแอป รุ่น บัญชี และนโยบายองค์กร การมี remote server ไม่ได้รับประกันว่า ChatGPT Work, Claude Cowork หรือ Antigravity ทุกบัญชีจะรองรับ ต้องทดสอบกับแอปที่ใช้อยู่จริง</p></details><details><summary>ขึ้น timeout หรือเข้าเว็บไซต์ไม่ได้</summary><p>ตรวจการเข้าถึง HTTPS จากเครือข่ายของแอป Domain และ OAuth ไม่ได้แก้การบล็อกของ proxy หรือ firewall โดยอัตโนมัติ อย่าส่ง key ในแชตเพื่อแก้ปัญหานี้</p></details><details><summary>สิทธิ์ไม่พอ หรือหมดอายุ</summary><p>เริ่มเชื่อมใหม่จากแอป แล้วตรวจรายการสิทธิ์ในหน้าอนุญาต คุณไม่ต้องคัดลอก token ไปให้ AI หาก callback ไม่ได้รับอนุญาต ให้ผู้ดูแลตรวจ URL จากแอปก่อนเพิ่มลงรายการอนุญาต</p></details><details><summary>ต้องใช้ Terminal ไหม?</summary><p>วิธี Remote MCP ไม่ต้องใช้ Terminal เพื่อกรอก key แต่ตัวแอปอาจมีวิธีเพิ่ม server ของตัวเอง วิธี Local CLI เดิมยังอยู่ใน Advanced สำหรับแอปที่ไม่รองรับ OAuth</p></details></section>
</article></div>
<script>
const status=document.getElementById('copy-status');
async function copy(text){try{await navigator.clipboard.writeText(text);status.textContent='คัดลอกแล้ว'}catch{status.textContent='คัดลอกไม่ได้ กรุณาเลือกข้อความแล้วคัดลอกเอง หรือเปิด Markdown'}}
document.getElementById('copy-url').addEventListener('click',()=>copy(document.getElementById('server-url').textContent.trim()));
document.getElementById('copy-page').addEventListener('click',async()=>{try{const response=await fetch('/docs/remote-mcp.md');if(!response.ok)throw new Error();await copy(await response.text())}catch{status.textContent='โหลดคู่มือไม่ได้ กรุณาเปิดลิงก์ Markdown'}});
</script></body></html>
